### PR TITLE
Rather dirty hack to automatically reopen a lost serial interface.

### PR DESCRIPTION
**Pull request by vdkeybus**
As proposed in forum, a modification to allow a lost serial connection to be re-established. It is dirty in the sense that it will most likely not work for interfaces also used as output (since the reopen cannot be done on the companion fd without close studying / reworking of the data structures).

### CODE REVIEW

**Comment by stripydog** [comment]
Jeroen,

I haven't forgotten this and many thanks for submitting.  I'm working on a
different solution to achieve the same end (should be available soon).  One
issue is that with bi-directional interfaces either the write side or the
read side, which are two different threads,  can be the first to detect a
problem with the interface so there needs to be a mechanism to ensure that
only one thread is responsible for the re-open.  Also the init_* routines
are not necessarily thread safe: they normally happen when kplex is running
single threaded on startup, so calling them later would require cleanup of
non-thread-safe elements.  That last part will happen for kplex 2.0 where I
want to be able to dynamically add and remove interfaces without stopping
other threads so perhaps what I am looking at here is a temporary solution.

I compared your solution and mine and note that there are some areas where
yours is much better, notably being more generic with a reopen routine
linked to the interface structure.  Of course I'd also have to modify the
tcp persistent code to work with that.

So I am still working on this: I won't take the pull request here but I
will take some of the ideas.  I'll let you know when it's finished and look
forward to your feedback

Keith

**Comment by vdkeybus** [comment]
Keith,

I only had to deal with a flaky NMEA0183 data source, which explains why I have not run into the problem of dealing with reader and writer threads. But you are right, it is not easy to solve this in an elegant fashion. When I find myself in such a situation, it is usually indicative of a not-so-optimal architecture design.

Just a thought: could the same functionality not be obtained by having a serial NMEA-to-IP bridge that's instanced multiple times ? And let the highly optimized Linux network stack and 'netfilter' do the hard multiplexing work ?

By all means, go ahead and use whatever you find useful in my patch.

Jeroen.



On a daily basis I have to deal with this kind of problems (networks and concurrent threads in Linux)Usually, when I'm faced with this

**Comment by stripydog** [comment]
When I find myself in such a situation, it is usually indicative of a
> not-so-optimal architecture design.
>
It was fine when it started...it's grown more complex as more has been
added.  The "2.0" should be a major re-write incorporating all the lessons
learned.

> Just a thought: could the same functionality not be obtained by having a
> serial NMEA-to-IP bridge that's instanced multiple times ? And let the
> highly optimized Linux network stack and 'netfilter' do the hard
> multiplexing work ?
>
There's many ways to do this. If you have a look at Frank Baudet's Muplex
<http://marinux.tuxfamily.org/#MUPLEX> he uses  socat to multiplex inputs
on the loopback interface.  socat could be used very trivially in a simple
serial to IP bridge.  kplex is probably overkill for some things but it
does have a number of "advanced" features for specifically dealing with
NMEA-0183 data (which socat, being a general tool, doesn't)

**Comment by stripydog** [comment]
Serial reconnection won't make it into the next release: sorry.  I revisited the tcp reconnection code with a view to overhauling things and realised that dealing with synchronising reconnections for blocking reader and writer threads is something of a multithreading nightmare.  I (hopefully) fixed the tcp reconnection issues but it's over-complicated so for the next major version I'll drop the separate-reader-and-writer-thread-per-interface idea which should vastly simplify things

**Comment by stripydog** [comment]
I've got a prototype change in the "new serial" branch here on github. Not well tested so far: seems to work with a serial to USB adaptor connected to my mac but haven't tested on linux/pi yet

**Comment by stripydog** [comment]
MK 1 persist now in develop branch (but has issues). Working on better version...

**Comment by stripydog** [comment]
Actually my code in the develop branch for this has some issues: it seems to work but it's flawed so currently working on a complete overhaul...

**Pull request closed without merging**
