### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by jwillmer**
- Dockerfile for building the app as a container
- docker-compose example
- Update of readme

After merge:
Go into cocker-compose.yml and change repository url.

Future:
Think about deploying the image on [docker hub](https://hub.docker.com/). If it is deployed on docker hub you can remove the build command in the docker-compose file and rename the image to  `stripydog/kplex:latest` (if you use stripydog as account name in docker hub)

### CODE REVIEW

**Comment by jwillmer** [comment]
You can make the build image a lot smaller when using Alpine image. My implementation was just a trade of between I need it now and I want to give something back. So were is potential for improvements depending how much you like to support docker.

**Comment by jwillmer** [comment]
Sorry can u recap? I do not understand what you like me to do.

**Comment by stripydog** [comment]
I don't merge anything to the master branch: all pull requests should go into the develop branch (I should find somewhere to advertise that on GitHub: I'm certainly no GitHub expert).  There doesn't look like any conflicts with your pull request in that branch so it shouldn't be a problem.

The Makefile in the develop branch tests for the existence of /usr/share/man/man1 and should create it. This should fix the problem you encountered with the master branch so the "mkdir" you do in the docker file should be unnecessary and can be removed.

If you wouldn't mind, could you:
- check out the develop branch of kplex
- removing the mkdir of /usr/share/man/man1 from your docker file (this should be unnecessary)
- check it does indeed work
- update the pull request
....and I'll merge it into the develop branch.

If you don't have time I can try and do it myself next week.

Between releases only critical bug fixes go into "master".  "develop" should be a fairly stable branch and it's what is used by openplotter.  New features and minor bug fixes go there after testing.  Just before a new release, "develop" is branched into a release branch and frozen.  Any bug fixes arising from testing are done to that release branch and when the release is  considered good, the release branch gets merged into both develop and master.

**Comment by jwillmer** [comment]
- mkfile removed from Dockerfile
- Build path updated to this repository
- I saw you already updated the branch so nothing to do for me

**Pull request merged**
